name: (Continuous Integration/Continuous Delivery)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "24"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-manager:latest

  deploy:
    name: Deploy to Oracle Cloud
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ORACLE_SSH_KEY }}
          known_hosts: ${{ secrets.ORACLE_KNOWN_HOSTS }}

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/finance-manager:latest
            sudo docker stop finance-manager || true
            sudo docker rm finance-manager || true
            sudo docker run -d --name finance-manager -p 8080:8080 \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_SECRET="${{secrets.JWT_SECRET}}" \
              -e FRONTEND_HOST="${{secrets.FRONTEND_HOST}}" \
              -e MAIL_USERNAME="${{secrets.MAIL_USERNAME}}" \
              -e MAIL_PASSWORD="${{secrets.MAIL_PASSWORD}}" \
              -e MAIL_FROM="${{secrets.MAIL_FROM}}" \
              --network monitoring-net \
              ${{ secrets.DOCKERHUB_USERNAME }}/finance-manager:latest
